### ISSUE TITLE
Everything seems fine but no scrobble

### ISSUE THREAD

**Issue by robinmayol** [GioF71/mpd-subsonic-scrobbler#22]
Hi!

Thank you for you hard work!

I'm pretty sure I have setup everything correctly. I can run the program and see this output:

```
subsonic-scrobbler  | mpd-subsonic-scrobbler version 0.2.0
subsonic-scrobbler  | SLEEP_TIME: [1000] msec
subsonic-scrobbler  | MIN_COVERAGE: [10%]
subsonic-scrobbler  | ENOUGH_PLAYBACK_SEC: [10 sec]
subsonic-scrobbler  | VERBOSE: [True]
subsonic-scrobbler  | server[0].friendly_name=[navidrome]
subsonic-scrobbler  | server[0].base_url=[http://192.168.191.61]
subsonic-scrobbler  | server[0].port=[4533]
subsonic-scrobbler  | server[0].user=[****]
subsonic-scrobbler  | server[0].password=[****]
subsonic-scrobbler  | mpd[0].friendly_name=[mpd]
subsonic-scrobbler  | mpd[0].host=[localhost]
subsonic-scrobbler  | mpd[0].port=[6600]
subsonic-scrobbler  | Current mpd state for index 0 [mpd] is [stop]
subsonic-scrobbler  | Current mpd state for index 0 [mpd] is [play]
```

But Navidrome doesn't update the "recently played" page with what I play via MPD, neither does it show mpd-subsonic-scrobbler in the list of players (not sure if it should). I would also imagine that the scrobbling event should show up in the verbose output when it happens. The only events that seem to be registered are play / pause and stop. When I stop it says 

```
subsonic-scrobbler  | Remove some data from context for index 0 ...
subsonic-scrobbler  | Data removal for index 0 complete.
``` 

I have tried to change the subsonic base url to http://localhost but to no avail.

Here is my docker-compose:

```
---
version: "3"

services:
  scrobbler:
    image: giof71/mpd-subsonic-scrobbler:latest
    container_name: subsonic-scrobbler
    network_mode: "host"
    environment:
      - MPD_FRIENDLY_NAME=mpd
      - MPD_HOST=localhost
      - MPD_PORT=6600
      - SUBSONIC_FRIENDLY_NAME=navidrome
      - SUBSONIC_BASE_URL=http://192.168.191.61
      - SUBSONIC_PORT=4533
      - SUBSONIC_USER=****
      - SUBSONIC_PASSWORD=****
      - MIN_COVERAGE=10
      - ENOUGH_PLAYBACK_SEC=10
      - VERBOSE=1
      - REDACT_CREDENTIALS=0
    restart: unless-stopped
```

Am I missing something?
